------------------------- MODULE L2Proofs -------------------------
(***************************************************************************)
(* Level 2's proof module: 40 lemmas, every one a five-level tree,        *)
(* citing level 1 at one INSTANCE hop and level 0 at two.                  *)
(*                                                                        *)
(* GENERATED by harness/gen_l2proofs.py -- do not edit by hand.  The shape *)
(* is a function of the lemma index, with no randomness, so regenerating   *)
(* is byte-identical and any diff means the generator changed.             *)
(***************************************************************************)
EXTENDS L2, TLAPS

\* The assumption bundle.  Every instantiated theorem below carries the
\* ASSUMEs of the module it came from as hypotheses of an ASSUME/PROVE, so
\* each citation has to discharge them.  Stating them once and citing this
\* lemma is what a real refinement proof does -- and getting the INSTANCE
\* hop count wrong here is the mistake CiteTrap.tla is about: these
\* assumptions reached level 1 by EXTENDS, so one hop later they are
\* L1!IsFiniteSet, not L1!L0!IsFiniteSet.
LEMMA Asm ==
    /\ L1!IsFiniteSet(Ids) /\ "none" \notin Ids
    /\ L1!IsFiniteSet(Buffers) /\ Buffers # {}
  BY FiniteIds, NoneNotAnId, FiniteBuffers, Zenon
  DEF L1!IsFiniteSet, IsFiniteSet

\* And the same bundle one hop further down, because the hop count of the
\* assumptions equals the hop count of the theorem being cited.  A level-0
\* theorem reached through level 1's own instance carries level 0's ASSUMEs
\* renamed twice, so Asm above does not discharge them and this one does.
LEMMA AsmDown ==
    /\ L1!L0!IsFiniteSet(Ids) /\ "none" \notin Ids
  BY FiniteIds, NoneNotAnId, Zenon
  DEF L1!L0!IsFiniteSet, IsFiniteSet

\* Carried once and reused by every level-0 citation below: the refinement
\* is what lets a level-2 proof reach two INSTANCE hops down.
LEMMA RefinesDown == L1!IndInv => L1!L0!IndInv
  BY Asm, L1!RefinesL0, Zenon

LEMMA Bundle0 ==
    L1!IndInv => L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q1 /\ L1!Q2
    <2>1. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q3 /\ L1!Q4 /\ L1!Q5
    <2>1. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle1 ==
    L1!IndInv => L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q4 /\ L1!Q5 /\ L1!Q6
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q6 /\ L1!Q7
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle2 ==
    L1!IndInv => L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q7 /\ L1!Q8
    <2>1. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
    <2>1. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle3 ==
    L1!IndInv => L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P4 /\ L1!L0!P5
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle4 ==
    L1!IndInv => L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
    <2>1. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle5 ==
    L1!IndInv => L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q2 /\ L1!Q3
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q4 /\ L1!Q5 /\ L1!Q6
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle6 ==
    L1!IndInv => L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q3 /\ L1!Q4
    <2>1. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q5 /\ L1!Q6 /\ L1!Q7
    <2>1. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle7 ==
    L1!IndInv => L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q6 /\ L1!Q7 /\ L1!Q8
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q8 /\ L1!L0!P1
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle8 ==
    L1!IndInv => L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5
    <2>1. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle9 ==
    L1!IndInv => L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P6 /\ L1!L0!P7
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle10 ==
    L1!IndInv => L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q1 /\ L1!Q2 /\ L1!Q3
    <2>1. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle11 ==
    L1!IndInv => L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q2 /\ L1!Q3 /\ L1!Q4
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q4 /\ L1!Q5
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q6 /\ L1!Q7 /\ L1!Q8
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle12 ==
    L1!IndInv => L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q5 /\ L1!Q6
    <2>1. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q7 /\ L1!Q8 /\ L1!L0!P1
    <2>1. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle13 ==
    L1!IndInv => L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P2 /\ L1!L0!P3
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle14 ==
    L1!IndInv => L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7
    <2>1. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle15 ==
    L1!IndInv => L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P8 /\ L1!Q1
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q2 /\ L1!Q3 /\ L1!Q4
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle16 ==
    L1!IndInv => L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q1 /\ L1!Q2
    <2>1. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q3 /\ L1!Q4 /\ L1!Q5
    <2>1. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle17 ==
    L1!IndInv => L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q4 /\ L1!Q5 /\ L1!Q6
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q6 /\ L1!Q7
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle18 ==
    L1!IndInv => L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q7 /\ L1!Q8
    <2>1. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
    <2>1. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle19 ==
    L1!IndInv => L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P4 /\ L1!L0!P5
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle20 ==
    L1!IndInv => L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
    <2>1. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle21 ==
    L1!IndInv => L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q2 /\ L1!Q3
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q4 /\ L1!Q5 /\ L1!Q6
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle22 ==
    L1!IndInv => L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q3 /\ L1!Q4
    <2>1. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q5 /\ L1!Q6 /\ L1!Q7
    <2>1. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle23 ==
    L1!IndInv => L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q6 /\ L1!Q7 /\ L1!Q8
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q8 /\ L1!L0!P1
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle24 ==
    L1!IndInv => L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5
    <2>1. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle25 ==
    L1!IndInv => L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P6 /\ L1!L0!P7
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle26 ==
    L1!IndInv => L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q1 /\ L1!Q2 /\ L1!Q3
    <2>1. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle27 ==
    L1!IndInv => L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q2 /\ L1!Q3 /\ L1!Q4
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q4 /\ L1!Q5
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q6 /\ L1!Q7 /\ L1!Q8
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle28 ==
    L1!IndInv => L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q5 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q5 /\ L1!Q6
    <2>1. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q7 /\ L1!Q8 /\ L1!L0!P1
    <2>1. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle29 ==
    L1!IndInv => L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P2 /\ L1!L0!P3
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle30 ==
    L1!IndInv => L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7
    <2>1. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle31 ==
    L1!IndInv => L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P8 /\ L1!Q1
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q2 /\ L1!Q3 /\ L1!Q4
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle32 ==
    L1!IndInv => L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q1 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q1 /\ L1!Q2
    <2>1. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q3 /\ L1!Q4 /\ L1!Q5
    <2>1. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle33 ==
    L1!IndInv => L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q4 /\ L1!Q5 /\ L1!Q6
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q6 /\ L1!Q7
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle34 ==
    L1!IndInv => L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q7 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q7 /\ L1!Q8
    <2>1. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3
    <2>1. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle35 ==
    L1!IndInv => L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4 /\ L1!L0!P4 /\ L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!L0!P4 /\ L1!L0!P5
    <2>1. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8
    <2>1. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle36 ==
    L1!IndInv => L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P5 /\ L1!L0!P6 /\ L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P5 /\ L1!L0!P6
    <2>1. L1!L0!P5
      <3>1. L1!L0!IndInv => L1!L0!P5
        <4>1. L1!L0!P5
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P6
      <3>1. L1!L0!IndInv => L1!L0!P6
        <4>1. L1!L0!P6
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!L0!P7 /\ L1!L0!P8 /\ L1!Q1
    <2>1. L1!L0!P7
      <3>1. L1!L0!IndInv => L1!L0!P7
        <4>1. L1!L0!P7
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle37 ==
    L1!IndInv => L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!L0!P8 /\ L1!Q1 /\ L1!Q2 /\ L1!Q2 /\ L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!L0!P8 /\ L1!Q1 /\ L1!Q2
    <2>1. L1!L0!P8
      <3>1. L1!L0!IndInv => L1!L0!P8
        <4>1. L1!L0!P8
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!Q1
      <3>1. L1!IndInv => L1!Q1
        <4>1. L1!IndInv => L1!Q1
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q2 /\ L1!Q3
    <2>1. L1!Q2
      <3>1. L1!IndInv => L1!Q2
        <4>1. L1!IndInv => L1!Q2
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!Q4 /\ L1!Q5 /\ L1!Q6
    <2>1. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Bundle38 ==
    L1!IndInv => L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q3 /\ L1!Q4 /\ L1!Q5 /\ L1!Q6 /\ L1!Q7
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q3 /\ L1!Q4
    <2>1. L1!Q3
      <3>1. L1!IndInv => L1!Q3
        <4>1. L1!IndInv => L1!Q3
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q4
      <3>1. L1!IndInv => L1!Q4
        <4>1. L1!IndInv => L1!Q4
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2. L1!Q5 /\ L1!Q6 /\ L1!Q7
    <2>1. L1!Q5
      <3>1. L1!IndInv => L1!Q5
        <4>1. L1!IndInv => L1!Q5
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Bundle39 ==
    L1!IndInv => L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
  <1> SUFFICES ASSUME L1!IndInv
               PROVE  L1!Q6 /\ L1!Q7 /\ L1!Q8 /\ L1!Q8 /\ L1!L0!P1 /\ L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1. L1!Q6 /\ L1!Q7 /\ L1!Q8
    <2>1. L1!Q6
      <3>1. L1!IndInv => L1!Q6
        <4>1. L1!IndInv => L1!Q6
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!Q7
      <3>1. L1!IndInv => L1!Q7
        <4>1. L1!IndInv => L1!Q7
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2. L1!Q8 /\ L1!L0!P1
    <2>1. L1!Q8
      <3>1. L1!IndInv => L1!Q8
        <4>1. L1!IndInv => L1!Q8
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!P1
      <3>1. L1!L0!IndInv => L1!L0!P1
        <4>1. L1!L0!P1
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3. L1!L0!P2 /\ L1!L0!P3 /\ L1!L0!P4
    <2>1. L1!L0!P2
      <3>1. L1!L0!IndInv => L1!L0!P2
        <4>1. L1!L0!P2
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!P3
      <3>1. L1!L0!IndInv => L1!L0!P3
        <4>1. L1!L0!P3
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!P4
      <3>1. L1!L0!IndInv => L1!L0!P4
        <4>1. L1!L0!P4
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

=====================================================================
