------------------------- MODULE L2Proofs -------------------------
(***************************************************************************)
(* Level 2's proof module: 40 lemmas over the two levels below.           *)
(*                                                                        *)
(* Two kinds.  A Cite lemma keeps every operator opaque and chains          *)
(* instantiated theorems four or five levels deep -- what it exercises is  *)
(* the context, which carries every definition of both levels below        *)
(* whether or not the goal mentions it.  An Open lemma names definitions   *)
(* in DEF, so the bodies of the invariants really enter the obligation --  *)
(* which is what a proof does when it opens an invariant to reach one      *)
(* conjunct, and the only way a definition's weight reaches a prover.      *)
(*                                                                        *)
(* GENERATED by harness/gen_l2proofs.py -- do not edit by hand.  The shape *)
(* is a function of the lemma index, with no randomness, so regenerating   *)
(* is byte-identical and any diff means the generator changed.             *)
(***************************************************************************)
EXTENDS L2, TLAPS

\* The assumption bundle.  Every instantiated theorem below carries the
\* ASSUMEs of the module it came from as hypotheses of an ASSUME/PROVE, so
\* each citation has to discharge them.  Getting the hop count wrong here
\* is the mistake CiteTrap.tla is about: these assumptions reached level 1
\* by EXTENDS, so one INSTANCE hop later they are L1!IsFiniteSet, not
\* L1!L0!IsFiniteSet.
LEMMA Asm ==
    /\ L1!IsFiniteSet(Ids) /\ "none" \notin Ids
    /\ L1!IsFiniteSet(Slots) /\ Slots # {}
    /\ L1!IsFiniteSet(Buffers) /\ Buffers # {}
    /\ Ceiling \in Nat \ {0}
  BY FiniteIds, FiniteSlots, NoneNotAnId, FiniteBuffers, CeilingPositive,
     Zenon
  DEF L1!IsFiniteSet, IsFiniteSet

\* And the same bundle one hop further down, because the hop depth of the
\* assumptions equals the hop depth of the theorem being cited.  A level-0
\* theorem reached through level 1's own instance carries level 0's ASSUMEs
\* renamed twice, so Asm above does not discharge them and this one does.
LEMMA AsmDown ==
    /\ L1!L0!IsFiniteSet(Ids) /\ "none" \notin Ids
    /\ L1!L0!IsFiniteSet(Slots) /\ Slots # {}
  BY FiniteIds, FiniteSlots, NoneNotAnId, Zenon
  DEF L1!L0!IsFiniteSet, IsFiniteSet

\* Carried once and reused by every level-0 citation below: the refinement
\* is what lets a level-2 proof reach two INSTANCE hops down.
LEMMA RefinesDown == L1!IndInv => L1!L0!IndInv
  BY Asm, L1!RefinesL0, Zenon

LEMMA Cite0 ==
    L1!IndInv =>
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite1 ==
    L1!IndInv =>
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
    <2>1. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open2 ==
    L1!IndInv =>
        /\ L1!ChargeUnderCeiling
        /\ L1!L0!SlotsAreNotShared
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ChargeUnderCeiling
                 /\ L1!L0!SlotsAreNotShared
    OBVIOUS
  <1>1. L1!ChargeUnderCeiling
    <2>1. L1!IndInv => L1!ChargeUnderCeiling
      <3>1. L1!ChargeUnderCeiling
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv, L1!SafetyCore
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!SlotsAreNotShared
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!SlotsAreNotShared
          <5>1. L1!L0!SlotsAreNotShared
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite3 ==
    L1!IndInv =>
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
    <2>1. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Cite4 ==
    L1!IndInv =>
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Open5 ==
    L1!IndInv =>
        /\ L1!HeldAgreesWithArena
        /\ L1!L0!OwnedImpliesQueueable
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!HeldAgreesWithArena
                 /\ L1!L0!OwnedImpliesQueueable
    OBVIOUS
  <1>1. L1!HeldAgreesWithArena
    <2>1. L1!IndInv => L1!HeldAgreesWithArena
      <3>1. L1!HeldAgreesWithArena
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv, L1!SafetyCore
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!OwnedImpliesQueueable
            BY <4>1 DEF L1!L0!IndInv
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite6 ==
    L1!IndInv =>
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite7 ==
    L1!IndInv =>
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
    <2>1. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
    <2>1. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open8 ==
    L1!IndInv =>
        /\ L1!BufferTypeOK
        /\ L1!L0!QueueBounded
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!BufferTypeOK
                 /\ L1!L0!QueueBounded
    OBVIOUS
  <1>1. L1!BufferTypeOK
    <2>1. L1!IndInv => L1!BufferTypeOK
      <3>1. L1!BufferTypeOK
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv, L1!SafetyCore
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!QueueBounded
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!QueueBounded
          <5>1. L1!L0!QueueBounded
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite9 ==
    L1!IndInv =>
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Cite10 ==
    L1!IndInv =>
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Open11 ==
    L1!IndInv =>
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
    OBVIOUS
  <1>1. L1!RefinementCoupling
    <2>1. L1!IndInv => L1!RefinementCoupling
      <3>1. L1!RefinementCoupling
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!TypeOK
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!TypeOK
          <5>1. L1!L0!TypeOK
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite12 ==
    L1!IndInv =>
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite13 ==
    L1!IndInv =>
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
    <2>1. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
    <2>1. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
    <2>1. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open14 ==
    L1!IndInv =>
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!L0!ClosingDrains
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!L0!ClosingDrains
    OBVIOUS
  <1>1. L1!NoBufferOutlivesItsCall
    <2>1. L1!IndInv => L1!NoBufferOutlivesItsCall
      <3>1. L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!ClosingDrains
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!ClosingDrains
          <5>1. L1!L0!ClosingDrains
            BY <4>1 DEF L1!L0!IndInv
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite15 ==
    L1!IndInv =>
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
    <2>1. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Cite16 ==
    L1!IndInv =>
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Open17 ==
    L1!IndInv =>
        /\ L1!ArenaRespectsPhase
        /\ L1!L0!PhaseMatchesLiveness
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ArenaRespectsPhase
                 /\ L1!L0!PhaseMatchesLiveness
    OBVIOUS
  <1>1. L1!ArenaRespectsPhase
    <2>1. L1!IndInv => L1!ArenaRespectsPhase
      <3>1. L1!ArenaRespectsPhase
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!PhaseMatchesLiveness
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!PhaseMatchesLiveness
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite18 ==
    L1!IndInv =>
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite19 ==
    L1!IndInv =>
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
    <2>1. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open20 ==
    L1!IndInv =>
        /\ L1!CreditMatchesArena
        /\ L1!L0!NoOrphanPayload
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!CreditMatchesArena
                 /\ L1!L0!NoOrphanPayload
    OBVIOUS
  <1>1. L1!CreditMatchesArena
    <2>1. L1!IndInv => L1!CreditMatchesArena
      <3>1. L1!CreditMatchesArena
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!NoOrphanPayload
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!NoOrphanPayload
          <5>1. L1!L0!NoOrphanPayload
            BY <4>1 DEF L1!L0!IndInv
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite21 ==
    L1!IndInv =>
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
    <2>1. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Cite22 ==
    L1!IndInv =>
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Open23 ==
    L1!IndInv =>
        /\ L1!ArenaCoversQueue
        /\ L1!L0!JournalMentionsKnownIds
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ArenaCoversQueue
                 /\ L1!L0!JournalMentionsKnownIds
    OBVIOUS
  <1>1. L1!ArenaCoversQueue
    <2>1. L1!IndInv => L1!ArenaCoversQueue
      <3>1. L1!ArenaCoversQueue
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!JournalMentionsKnownIds
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!JournalMentionsKnownIds
            BY <4>1 DEF L1!L0!IndInv
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite24 ==
    L1!IndInv =>
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
    <2>1. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite25 ==
    L1!IndInv =>
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open26 ==
    L1!IndInv =>
        /\ L1!ChargeUnderCeiling
        /\ L1!L0!SlotsAreNotShared
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ChargeUnderCeiling
                 /\ L1!L0!SlotsAreNotShared
    OBVIOUS
  <1>1. L1!ChargeUnderCeiling
    <2>1. L1!IndInv => L1!ChargeUnderCeiling
      <3>1. L1!ChargeUnderCeiling
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv, L1!SafetyCore
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!SlotsAreNotShared
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!SlotsAreNotShared
          <5>1. L1!L0!SlotsAreNotShared
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite27 ==
    L1!IndInv =>
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
    <2>1. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Cite28 ==
    L1!IndInv =>
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Open29 ==
    L1!IndInv =>
        /\ L1!HeldAgreesWithArena
        /\ L1!L0!OwnedImpliesQueueable
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!HeldAgreesWithArena
                 /\ L1!L0!OwnedImpliesQueueable
    OBVIOUS
  <1>1. L1!HeldAgreesWithArena
    <2>1. L1!IndInv => L1!HeldAgreesWithArena
      <3>1. L1!HeldAgreesWithArena
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv, L1!SafetyCore
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!OwnedImpliesQueueable
            BY <4>1 DEF L1!L0!IndInv
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite30 ==
    L1!IndInv =>
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
    <2>1. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
    <2>1. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite31 ==
    L1!IndInv =>
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
    <2>1. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
    <2>1. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open32 ==
    L1!IndInv =>
        /\ L1!BufferTypeOK
        /\ L1!L0!QueueBounded
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!BufferTypeOK
                 /\ L1!L0!QueueBounded
    OBVIOUS
  <1>1. L1!BufferTypeOK
    <2>1. L1!IndInv => L1!BufferTypeOK
      <3>1. L1!BufferTypeOK
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv, L1!SafetyCore
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!QueueBounded
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!QueueBounded
          <5>1. L1!L0!QueueBounded
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite33 ==
    L1!IndInv =>
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
    <2>1. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Cite34 ==
    L1!IndInv =>
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
    <2>1. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Open35 ==
    L1!IndInv =>
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
    OBVIOUS
  <1>1. L1!RefinementCoupling
    <2>1. L1!IndInv => L1!RefinementCoupling
      <3>1. L1!RefinementCoupling
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!TypeOK
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!TypeOK
          <5>1. L1!L0!TypeOK
            BY <4>1 DEF L1!L0!IndInv, L1!L0!SafetyCore
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite36 ==
    L1!IndInv =>
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!L0!ClosingDrains
                 /\ L1!L0!OwnedImpliesQueueable
                 /\ L1!L0!NoOrphanPayload
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!L0!ClosingDrains
        /\ L1!L0!OwnedImpliesQueueable
    <2>1. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!OwnedImpliesQueueable
      <3>1. L1!L0!IndInv => L1!L0!OwnedImpliesQueueable
        <4>1. L1!L0!OwnedImpliesQueueable
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>2.
        /\ L1!L0!NoOrphanPayload
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
    <2>1. L1!L0!NoOrphanPayload
      <3>1. L1!L0!IndInv => L1!L0!NoOrphanPayload
        <4>1. L1!L0!NoOrphanPayload
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite37 ==
    L1!IndInv =>
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!BufferTypeOK
                 /\ L1!HeldAgreesWithArena
                 /\ L1!ChargeUnderCeiling
                 /\ L1!ArenaCoversQueue
                 /\ L1!CreditMatchesArena
                 /\ L1!ArenaRespectsPhase
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!BufferTypeOK
        /\ L1!HeldAgreesWithArena
        /\ L1!ChargeUnderCeiling
    <2>1. L1!BufferTypeOK
      <3>1. L1!IndInv => L1!BufferTypeOK
        <4>1. L1!IndInv => L1!BufferTypeOK
          BY Asm, L1!Q1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!HeldAgreesWithArena
      <3>1. L1!IndInv => L1!HeldAgreesWithArena
        <4>1. L1!IndInv => L1!HeldAgreesWithArena
          BY Asm, L1!Q2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!ChargeUnderCeiling
      <3>1. L1!IndInv => L1!ChargeUnderCeiling
        <4>1. L1!IndInv => L1!ChargeUnderCeiling
          BY Asm, L1!Q3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!ArenaCoversQueue
        /\ L1!CreditMatchesArena
    <2>1. L1!ArenaCoversQueue
      <3>1. L1!IndInv => L1!ArenaCoversQueue
        <4>1. L1!IndInv => L1!ArenaCoversQueue
          BY Asm, L1!Q4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!CreditMatchesArena
      <3>1. L1!IndInv => L1!CreditMatchesArena
        <4>1. L1!IndInv => L1!CreditMatchesArena
          BY Asm, L1!Q5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!ArenaRespectsPhase
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
    <2>1. L1!ArenaRespectsPhase
      <3>1. L1!IndInv => L1!ArenaRespectsPhase
        <4>1. L1!IndInv => L1!ArenaRespectsPhase
          BY Asm, L1!Q6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

LEMMA Open38 ==
    L1!IndInv =>
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!L0!ClosingDrains
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!L0!ClosingDrains
    OBVIOUS
  <1>1. L1!NoBufferOutlivesItsCall
    <2>1. L1!IndInv => L1!NoBufferOutlivesItsCall
      <3>1. L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv
          OBVIOUS
        <4>2. QED
          BY <4>1 DEF L1!IndInv
      <3>2. QED
        BY <3>1
    <2>2. QED
      BY <2>1
  <1>2. L1!L0!ClosingDrains
    <2>1. L1!L0!IndInv
      BY RefinesDown, Zenon
    <2>2. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. ASSUME L1!L0!IndInv
                     PROVE  L1!L0!ClosingDrains
          <5>1. L1!L0!ClosingDrains
            BY <4>1 DEF L1!L0!IndInv
          <5>2. QED
            BY <5>1
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, <2>1
    <2>3. QED
      BY <2>2
  <1>3. QED
    BY <1>1, <1>2

LEMMA Cite39 ==
    L1!IndInv =>
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
  <1> SUFFICES ASSUME L1!IndInv
               PROVE
                 /\ L1!NoBufferOutlivesItsCall
                 /\ L1!RefinementCoupling
                 /\ L1!L0!TypeOK
                 /\ L1!L0!SlotsAreNotShared
                 /\ L1!L0!PhaseMatchesLiveness
                 /\ L1!L0!QueueBounded
                 /\ L1!L0!JournalMentionsKnownIds
                 /\ L1!L0!ClosingDrains
    OBVIOUS
  <1>0. L1!L0!IndInv
    BY RefinesDown, Zenon
  <1>1.
        /\ L1!NoBufferOutlivesItsCall
        /\ L1!RefinementCoupling
        /\ L1!L0!TypeOK
    <2>1. L1!NoBufferOutlivesItsCall
      <3>1. L1!IndInv => L1!NoBufferOutlivesItsCall
        <4>1. L1!IndInv => L1!NoBufferOutlivesItsCall
          BY Asm, L1!Q7Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>2. L1!RefinementCoupling
      <3>1. L1!IndInv => L1!RefinementCoupling
        <4>1. L1!IndInv => L1!RefinementCoupling
          BY Asm, L1!Q8Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1
    <2>3. L1!L0!TypeOK
      <3>1. L1!L0!IndInv => L1!L0!TypeOK
        <4>1. L1!L0!TypeOK
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P1Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>2.
        /\ L1!L0!SlotsAreNotShared
        /\ L1!L0!PhaseMatchesLiveness
    <2>1. L1!L0!SlotsAreNotShared
      <3>1. L1!L0!IndInv => L1!L0!SlotsAreNotShared
        <4>1. L1!L0!SlotsAreNotShared
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P2Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!PhaseMatchesLiveness
      <3>1. L1!L0!IndInv => L1!L0!PhaseMatchesLiveness
        <4>1. L1!L0!PhaseMatchesLiveness
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P3Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. QED
      BY <2>1, <2>2
  <1>3.
        /\ L1!L0!QueueBounded
        /\ L1!L0!JournalMentionsKnownIds
        /\ L1!L0!ClosingDrains
    <2>1. L1!L0!QueueBounded
      <3>1. L1!L0!IndInv => L1!L0!QueueBounded
        <4>1. L1!L0!QueueBounded
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P4Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>2. L1!L0!JournalMentionsKnownIds
      <3>1. L1!L0!IndInv => L1!L0!JournalMentionsKnownIds
        <4>1. L1!L0!JournalMentionsKnownIds
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P5Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>3. L1!L0!ClosingDrains
      <3>1. L1!L0!IndInv => L1!L0!ClosingDrains
        <4>1. L1!L0!ClosingDrains
          <5>1. L1!L0!IndInv
            BY RefinesDown, Zenon
          <5>2. QED
            BY <5>1, Asm, AsmDown, L1!L0!P6Holds, Zenon
        <4>2. QED
          BY <4>1
      <3>2. QED
        BY <3>1, RefinesDown
    <2>4. QED
      BY <2>1, <2>2, <2>3
  <1>4. QED
    BY <1>1, <1>2, <1>3

=====================================================================
