--------------------------- MODULE Ladder4 ---------------------------
(* 4 INSTANCE declaration(s) of L1Theorems and one obligation.       *)
(* Only the instance count varies across Ladder1..4, so the           *)
(* per-obligation context is a direct reading of what one INSTANCE    *)
(* copies in, and nothing else.                                       *)
(*                                                                    *)
(* GENERATED by harness/instance_demo.sh -- do not edit by hand.      *)
EXTENDS L1State

J1 == INSTANCE L1Theorems
J2 == INSTANCE L1Theorems
J3 == INSTANCE L1Theorems
J4 == INSTANCE L1Theorems

THEOREM Probe == J1!IndInv => J1!SafetyCore
    BY J1!IndInvImpliesSafetyCore
=====================================================================
